---
engine_version: 0.4.6
file_version: 2023-03-07 13:32:04.460864000 Z
resources:
- name: delayed/backend/active_record/job
  preferences:
    visible: false
  updated_at: 2023-03-07 13:32:04.460864000 +00:00
configs:
- key: header.links
  value:
  - name: "⭐ Star on GitHub"
    path: https://github.com/motor-admin/motor-admin-rails
  updated_at: 2023-03-07 12:59:23.207736000 +00:00
queries: []
dashboards: []
forms: []
alerts: []
api_configs:
- id: 1
  name: origin
  url: "/"
  preferences: {}
  description: 
  updated_at: 2023-03-07 12:59:23.220124000 +00:00
