name: "Pull-request"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pipeline:
    permissions:
      deployments: write
      contents: read
    uses: ./.github/workflows/base.yaml
    with:
      ref: "origin/${{ github.event.pull_request.base.ref }}"
      environment: ci
      group: dev
      tests: unit, spec, static
      build: true
    secrets:
      ENVIRONMENT_FILE_ROOT: ${{ secrets.ENVIRONMENT_FILE_ROOT }}
      ENVIRONMENT_FILE_GROUP: ${{ secrets.ENVIRONMENT_FILE_DEV }}
      ENVIRONMENT_FILE_ENV: ${{ secrets.ENVIRONMENT_FILE_DEV_CI }}
#      SONAR_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
