name: "Push"

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    permissions:
      deployments: write
      contents: read
    uses: ./.github/workflows/base.yaml
    with:
      group: dev
      environment: dev01
      tests: static
      package-n-upload: true
      construct: true
      deploy: true
    secrets:
      ENVIRONMENT_FILE_ROOT: ${{ secrets.ENVIRONMENT_FILE_ROOT }}
      ENVIRONMENT_FILE_GROUP: ${{ secrets.ENVIRONMENT_FILE_DEV }}
      ENVIRONMENT_FILE_ENV: ${{ secrets.ENVIRONMENT_FILE_DEV_DEV01 }}
#      SONAR_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
